import AppKit
import UniformTypeIdentifiers
import XCTest
@testable import ClipboardManager

final class PasteboardReaderTests: XCTestCase {
    private func plainText(_ result: ReadResult) -> String? {
        if case .captured(let payload) = result, case .text(let text, _, _) = payload.content { return text }
        return nil
    }

    func testEmptyPasteboardIsSkipped() {
        let pb = TestSupport.pasteboard()
        guard case .skipped(let reason) = PasteboardReader.read(pb) else { return XCTFail("expected skip") }
        XCTAssertEqual(reason, .empty)
    }

    func testConcealedItemsAreNeverCaptured() {
        let pb = TestSupport.pasteboard()
        let item = NSPasteboardItem()
        item.setString("hunter2", forType: .string)
        item.setString("", forType: PasteboardReader.concealedType)
        pb.writeObjects([item])
        guard case .skipped(let reason) = PasteboardReader.read(pb) else { return XCTFail("expected skip") }
        XCTAssertEqual(reason, .concealed)
    }

    func testTransientAndAutoGeneratedAreSkipped() {
        for (type, expected) in [(PasteboardReader.transientType, SkipReason.transient),
                                 (PasteboardReader.autoGeneratedType, SkipReason.autoGenerated)] {
            let pb = TestSupport.pasteboard()
            let item = NSPasteboardItem()
            item.setString("x", forType: .string)
            item.setString("", forType: type)
            pb.writeObjects([item])
            guard case .skipped(let reason) = PasteboardReader.read(pb) else { return XCTFail("expected skip") }
            XCTAssertEqual(reason, expected)
        }
    }

    func testPlainText() {
        let pb = TestSupport.pasteboard()
        pb.setString("Hello\nworld", forType: .string)
        XCTAssertEqual(plainText(PasteboardReader.read(pb)), "Hello\nworld")
    }

    func testWhitespaceOnlyTextIsUnsupported() {
        let pb = TestSupport.pasteboard()
        pb.setString("  \n\t ", forType: .string)
        guard case .skipped(let reason) = PasteboardReader.read(pb) else { return XCTFail("expected skip") }
        XCTAssertEqual(reason, .unsupported)
    }

    func testRichTextFlagsAndKeepsRTF() throws {
        let pb = TestSupport.pasteboard()
        let attributed = NSAttributedString(string: "Bold", attributes: [.font: NSFont.boldSystemFont(ofSize: 12)])
        let rtf = try XCTUnwrap(attributed.rtf(from: NSRange(location: 0, length: 4), documentAttributes: [:]))
        let item = NSPasteboardItem()
        item.setString("Bold", forType: .string)
        item.setData(rtf, forType: .rtf)
        pb.writeObjects([item])
        guard case .captured(let payload) = PasteboardReader.read(pb),
              case .text(let text, let data, let isRich) = payload.content else { return XCTFail("expected text") }
        XCTAssertEqual(text, "Bold")
        XCTAssertTrue(isRich)
        XCTAssertEqual(data, rtf)
    }

    func testSingleURLTextBecomesLink() {
        let pb = TestSupport.pasteboard()
        pb.setString("https://example.com/path?q=1", forType: .string)
        guard case .captured(let payload) = PasteboardReader.read(pb),
              case .link(let url, let title) = payload.content else { return XCTFail("expected link") }
        XCTAssertEqual(url.host, "example.com")
        XCTAssertNil(title)
    }

    func testURLObjectWithTitle() {
        let pb = TestSupport.pasteboard()
        let item = NSPasteboardItem()
        item.setString("https://developer.apple.com/", forType: .URL)
        item.setString("https://developer.apple.com/", forType: .string)
        item.setString("Apple Developer", forType: PasteboardReader.urlNameType)
        pb.writeObjects([item])
        guard case .captured(let payload) = PasteboardReader.read(pb),
              case .link(_, let title) = payload.content else { return XCTFail("expected link") }
        XCTAssertEqual(title, "Apple Developer")
    }

    func testTextContainingURLStaysText() {
        let pb = TestSupport.pasteboard()
        pb.setString("see https://example.com for details", forType: .string)
        XCTAssertNotNil(plainText(PasteboardReader.read(pb)))
    }

    func testNonHTTPSchemesAreText() {
        let pb = TestSupport.pasteboard()
        pb.setString("javascript:alert(1)", forType: .string)
        XCTAssertNotNil(plainText(PasteboardReader.read(pb)))
    }

    func testImageWinsOverURLText() {
        let pb = TestSupport.pasteboard()
        pb.setData(TestSupport.pngData(width: 8, height: 8, transparent: false), forType: .png)
        pb.setString("https://example.com/image.png", forType: .string)
        guard case .captured(let payload) = PasteboardReader.read(pb),
              case .image(_, let uti) = payload.content else { return XCTFail("expected image") }
        XCTAssertEqual(uti, UTType.png.identifier)
    }

    func testProseWinsOverImage() {
        let pb = TestSupport.pasteboard()
        pb.setData(TestSupport.pngData(width: 8, height: 8, transparent: false), forType: .png)
        pb.setString("Quarterly totals\n1\t2\t3", forType: .string)
        XCTAssertNotNil(plainText(PasteboardReader.read(pb)))
    }

    func testFileURLsBecomeFiles() {
        let pb = TestSupport.pasteboard()
        pb.writeObjects([URL(fileURLWithPath: "/etc/hosts") as NSURL, URL(fileURLWithPath: "/etc/passwd") as NSURL])
        guard case .captured(let payload) = PasteboardReader.read(pb),
              case .files(let urls) = payload.content else { return XCTFail("expected files") }
        XCTAssertEqual(urls.map(\.path), ["/etc/hosts", "/etc/passwd"])
    }

    func testHashInputIsStableForSameText() {
        let a = TestSupport.pasteboard(); a.setString("same", forType: .string)
        let b = TestSupport.pasteboard(); b.setString("same", forType: .string)
        guard case .captured(let pa) = PasteboardReader.read(a), case .captured(let pb) = PasteboardReader.read(b) else { return XCTFail() }
        XCTAssertEqual(pa.hashInput, pb.hashInput)
    }
}
