import AppKit
import UniformTypeIdentifiers

enum CapturedContent {
    case text(String, rtf: Data?, isRich: Bool)
    case image(Data, uti: String)
    case link(URL, title: String?)
    case files([URL])
}

struct CapturedPayload {
    var content: CapturedContent
    /// Bytes that identify this clipboard content for duplicate detection.
    var hashInput: Data
}

enum SkipReason: String {
    case empty
    case concealed
    case transient
    case autoGenerated
    case unsupported
    case excludedApp
    case secureInput
}

enum ReadResult {
    case captured(CapturedPayload)
    case skipped(SkipReason)
}

/// Turns the current pasteboard contents into a typed payload. Must run on the main thread.
enum PasteboardReader {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let jpegType = NSPasteboard.PasteboardType(UTType.jpeg.identifier)
    static let urlNameType = NSPasteboard.PasteboardType("public.url-name")

    static func read(_ pasteboard: NSPasteboard) -> ReadResult {
        var allTypes = Set(pasteboard.types ?? [])
        for item in pasteboard.pasteboardItems ?? [] {
            allTypes.formUnion(item.types)
        }
        guard !allTypes.isEmpty else { return .skipped(.empty) }

        // Password-manager and helper-app markers: never persist these.
        if allTypes.contains(concealedType) { return .skipped(.concealed) }
        if allTypes.contains(transientType) { return .skipped(.transient) }
        if allTypes.contains(autoGeneratedType) { return .skipped(.autoGenerated) }

        // 1. File references (Finder copies, drag sources).
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !fileURLs.isEmpty {
            let joined = fileURLs.map(\.path).joined(separator: "\n")
            return .captured(CapturedPayload(content: .files(fileURLs), hashInput: Data(joined.utf8)))
        }

        let plain = pasteboard.string(forType: .string)
        let trimmed = plain?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let textURL = singleURL(in: trimmed)
        let image = richestImage(on: pasteboard)

        // 2. Images. When an app also supplies meaningful non-URL text (spreadsheets, rich editors) the text
        //    is the more useful representation; a bare URL next to an image is just the image's source.
        if let image {
            let textIsMeaningful = !trimmed.isEmpty && textURL == nil
            if !textIsMeaningful {
                return .captured(CapturedPayload(content: .image(image.data, uti: image.uti), hashInput: image.data))
            }
        }

        // 3. Links: either a public.url object or plain text that is exactly one http(s) URL.
        let urlObject = (pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: false]) as? [URL])?
            .first(where: { !$0.isFileURL })
        if let url = textURL ?? (trimmed.isEmpty ? urlObject : nil) {
            var title = pasteboard.string(forType: urlNameType)?.trimmingCharacters(in: .whitespacesAndNewlines)
            if title?.isEmpty == true || title == url.absoluteString { title = nil }
            return .captured(CapturedPayload(content: .link(url, title: title), hashInput: Data(url.absoluteString.utf8)))
        }

        // 4. Text, plain or rich.
        let rtf = pasteboard.data(forType: .rtf)
        let html = pasteboard.data(forType: .html)
        if let plain, !trimmed.isEmpty {
            return .captured(CapturedPayload(content: .text(plain, rtf: rtf, isRich: rtf != nil || html != nil),
                                             hashInput: Data(plain.utf8)))
        }
        if let rtf, let attributed = NSAttributedString(rtf: rtf, documentAttributes: nil),
           !attributed.string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .captured(CapturedPayload(content: .text(attributed.string, rtf: rtf, isRich: true),
                                             hashInput: Data(attributed.string.utf8)))
        }

        // 5. Image with no usable text fallback.
        if let image {
            return .captured(CapturedPayload(content: .image(image.data, uti: image.uti), hashInput: image.data))
        }

        return .skipped(.unsupported)
    }

    private static func richestImage(on pasteboard: NSPasteboard) -> (data: Data, uti: String)? {
        if let png = pasteboard.data(forType: .png) { return (png, UTType.png.identifier) }
        if let jpeg = pasteboard.data(forType: jpegType) { return (jpeg, UTType.jpeg.identifier) }
        if let tiff = pasteboard.data(forType: .tiff) { return (tiff, UTType.tiff.identifier) }
        return nil
    }

    static func singleURL(in text: String) -> URL? {
        guard !text.isEmpty, text.count < 4_096, !text.contains(where: \.isWhitespace),
              let url = URL(string: text), let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https", url.host != nil else {
            return nil
        }
        return url
    }
}
